config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :updates, only: [:index, :show, :create, :new]

  resources :tags, only: [:index]
  root to: "updates#index"
  get 'tags/:tag', to: 'updates#index', as: :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :updates, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag, foreign_key: "tag_id"
  belongs_to :user, foreign_key: "update_id", class_name: "Update"
end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  validates :title, uniqueness: { scope: :user_id }

  def self.tagged_with(name)
    tag_name = Tag.find_by!(category: name)
    taggings = Tagging.where(tag_id: tag_name)
    taggings.map do |tag|
      Update.find_by!(id: tag.update_id)
    end
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:category).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(category: n.strip).first_or_create!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :updates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  def index
    if @query.present? && params[:tag] # this does not work
      @updates = User.where("name ILIKE ?", "%#{params[:query]}%").first.updates.tagged_with(params[:tag]).reverse
    elsif params[:query].present?
      @updates = User.where("name ILIKE ?", "%#{params[:query]}%").first.updates.reverse
    elsif params[:tag]
      @updates = Update.tagged_with(params[:tag]).reverse
    else
      @updates = Update.order(created_at: :desc).limit(50)
    end
    @h1 = params[:tag] ? "##{params[:tag]}" : "Daily Updates"
  end

  def create
    @update = Update.new(title: form_params["title"], description: form_params['description'], user_id: form_params['user_id'])

    if one_a_day?
      flash[:notice] = "Only one update a day."
      redirect_to updates_path
      return
    end

    if @update.save
      custom_tags unless form_params["new_tags"].empty?
      select_tags if form_params['tag_ids'].length > 1
    else
      flash[:notice] = "Please enter a unique title."
    end
    redirect_to updates_path
  end

  def show
    @update = Update.find(params[:id])
  end

  private

  def select_tags
    form_params['tag_ids'][1..].each { |tag| Tagging.create!(tag_id: tag, update_id: @update.id) }
  end

  def custom_tags
    form_params["new_tags"].gsub(/\s+/, '').split(',').each do |new_tag|
      unless Tag.where("category ILIKE ?", new_tag).empty?
        last_tag = Tag.create!(category: new_tag)
        Tagging.create!(tag_id: last_tag.id, update_id: @update.id)
      end
    end
  end

  def one_a_day?
    prev_update = current_user.updates.last
    return prev_update && prev_update.created_at.to_date.to_fs(:long_ordinal) == DateTime.now.to_date.to_fs(:long_ordinal)
  end

  def form_params
    params.require(:update).permit(:title, :user_id, :description, :tag_list, :tag, { tag_ids: [] }, :tag_ids, :new_tags)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daily Updates</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container d-flex flex-column justify-content-center align-items-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://cdn0.iconfinder.com/data/icons/laptops-in-different-expressions/200/LP-512.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item p-3">
            <%= link_to "Home", updates_path, class: "nav-link" %>
          </li>
          <li class="nav-item p-3">
            <%= link_to "All Tags", tags_path, class: "nav-link" %>
          </li>
          <li class="nav-item p-3">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item p-3">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tags/index.html.erb
<h1 class="mt-4">Tags</h1>
<ul class="tag-list d-flex flex-wrap">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to "#{tag.category}", tag_path(tag.category) %>
      (<%= Tagging.where(tag_id: tag.id).count %>)
    </li>
  <% end %>
</ul>

app/views/updates/create.html.erb
<h1>Updates#create</h1>
<p>Find me in app/views/updates/create.html.erb</p>

app/views/updates/index.html.erb
<h1 class="mt-5"><%= @h1 %></h1>
<p class="mb-5 "><strong>Hi, <%= current_user.name %>.</strong></p>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary mb-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
  New Update
</button>

<!-- Search Bar -->
<%= form_with url: updates_path, method: :get, class: "d-flex mb-5 search-bar" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find updates by user"
  %>
  <%= submit_tag "Search", class: "btn-light" %>
<% end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Today's Update</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <div class="modal-body">
          <%= simple_form_for :update, method: :post, url: { action: "create" } do |f| %>
            <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
            <%= f.input :title %>
            <%= f.input :description %>
            <%= f.input :tag_ids, as: :select, collection: Tag.order(:category), label_method: :category, input_html: {multiple: true}, required: false %>
            <%= f.input :new_tags, required: false %>
        </div>
      <div class="modal-footer">
          <%= f.submit "Submit", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Updates -->
<div class="mb-3">
  <% @updates.each_with_index do |update, i| %>
    <div class="update-box d-flex align-items-end flex-column mb-4">
      <% if i == 0 || @updates[i - 1].created_at.to_date.to_fs(:long_ordinal) != update.created_at.to_date.to_fs(:long_ordinal) %>
        <p class="go-left mb-1"><%= update.created_at.to_date.to_fs(:long_ordinal) %></p>
      <% end %>
      <div class="d-flex justify-content-around info mb-1">
        <p><strong><%= update.user.name %>:</strong></p>
        <p><%= update.title %></p>
        <p><%= link_to "View Update", update_path(update) %></p>
      </div>
      <div class="tags mt-2">
        <p><%= raw update.tags.map(&:category).map { |t| link_to t, tag_path(t) }.join(', ') %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/updates/show.html.erb
<div class="show-update mt-4 mb-4">
  <p class="text-start mb-3"><%= @update.created_at.to_date.to_fs(:long_ordinal) %></p>
  <h2 class="mb-1"><%= @update.title.capitalize %></h2>
  <p class="mb-3"><strong>By <%= @update.user.name %></strong></p>
  <p><%= @update.description.capitalize %></p>
  <div class="tags mt-4">
    <p><%= raw @update.tags.map(&:category).map { |t| link_to t, tag_path(t) }.join(', ') %></p>
  </div>
</div>

<%= link_to "Go Back", updates_path, {class: "btn btn-light text-start"} %>